name: Linter

on: 
  push:
    branches: [main, pre-main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-skip:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel previous redundant builds
        uses: styfle/cancel-workflow-action@0.9.1
        with: 
          access_token: ${{ github.token }}

  linter: 
    runs-on: ubuntu-20.04
    steps: 
      - name: Checkout files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.13.4
      - name: Install depedencies
        run: pnpm install
      - name: Run Linter 
        run: pnpm linter
